#!/bin/bash
set -e

echo "========================================"
echo "Seqera Platform Smoke Test - tw CLI"
echo "========================================"
echo ""

# Load environment variables from .env if it exists
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
    echo "Loading environment variables from $ENV_FILE"
    set -a
    source "$ENV_FILE"
    set +a
    echo ""
fi

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v tw &> /dev/null; then
    echo "ERROR: tw CLI not found. Please install Seqera Platform CLI first."
    echo ""
    echo "Installation:"
    echo "  Homebrew:  brew install seqeralabs/tap/tw"
    echo "  Direct:    https://github.com/seqeralabs/tower-cli/releases/latest"
    echo ""
    echo "See: https://github.com/seqeralabs/tower-cli"
    echo ""
    exit 1
fi

echo "✓ Seqera Platform CLI found"

# Check tw login status
if ! tw info &> /dev/null; then
    echo "ERROR: Not logged in to Seqera Platform."
    echo "Please run: tw login"
    echo ""
    exit 1
fi

echo "✓ Logged in to Seqera Platform"
echo ""

# Check and prompt for TOWER_ACCESS_TOKEN
if [ -z "$TOWER_ACCESS_TOKEN" ]; then
    echo "TOWER_ACCESS_TOKEN not found in environment."
    echo "Enter your Seqera Platform access token:"
    read -r TOWER_ACCESS_TOKEN

    if [ -z "$TOWER_ACCESS_TOKEN" ]; then
        echo "ERROR: TOWER_ACCESS_TOKEN is required."
        exit 1
    fi

    # Save to .env file
    SAVE_TO_ENV=true
fi

echo "✓ TOWER_ACCESS_TOKEN configured"
export TOWER_ACCESS_TOKEN

# Save environment variables to .env if new ones were entered
if [ "$SAVE_TO_ENV" = true ]; then
    echo ""
    echo "Saving credentials to $ENV_FILE for future use..."

    # Create or update .env file
    {
        echo "# Seqera Platform credentials"
        echo "# Generated by test-tw.sh on $(date)"
        echo "TOWER_ACCESS_TOKEN=$TOWER_ACCESS_TOKEN"
        if [ -n "$TOWER_WORKSPACE_ID" ]; then
            echo "TOWER_WORKSPACE_ID=$TOWER_WORKSPACE_ID"
        fi
    } > "$ENV_FILE"

    # Ensure .env is in .gitignore
    if [ -f ".gitignore" ]; then
        if ! grep -q "^\.env$" .gitignore; then
            echo ".env" >> .gitignore
            echo "✓ Added .env to .gitignore"
        fi
    else
        echo ".env" > .gitignore
        echo "✓ Created .gitignore with .env"
    fi

    echo "✓ Credentials saved to $ENV_FILE"
fi

echo ""

# Check for workspaces
echo "Checking workspaces..."
tw workspaces list
if [ $? -ne 0 ]; then
    echo "ERROR: Unable to list workspaces."
    exit 1
fi

echo ""

# Check if workspace is already set from environment
if [ -n "$TOWER_WORKSPACE_ID" ]; then
    echo "Using workspace from environment: $TOWER_WORKSPACE_ID"
    WORKSPACE="$TOWER_WORKSPACE_ID"
    echo ""
else
    echo "Enter workspace in Organization/Workspace format"
    echo "(e.g., Quilt_Data/hackathon_2023):"
    read -r WORKSPACE

    if [ -z "$WORKSPACE" ]; then
        echo "ERROR: Workspace is required."
        exit 1
    fi

    # Save the workspace for future runs
    echo ""
    echo "Saving workspace to $ENV_FILE for future use..."

    # Append or update the .env file
    if [ -f "$ENV_FILE" ]; then
        # Remove old TOWER_WORKSPACE_ID if exists, then append new one
        grep -v "^TOWER_WORKSPACE_ID=" "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
        echo "TOWER_WORKSPACE_ID=$WORKSPACE" >> "${ENV_FILE}.tmp"
        mv "${ENV_FILE}.tmp" "$ENV_FILE"
    else
        echo "TOWER_WORKSPACE_ID=$WORKSPACE" >> "$ENV_FILE"
    fi
    echo "✓ Workspace saved"
    echo ""
fi

# Create work directory if it doesn't exist
mkdir -p work
PARAMS_FILE="work/params.yaml"

# Check if params file already exists and offer to reuse
if [ -f "$PARAMS_FILE" ]; then
    EXISTING_OUTDIR=$(grep "^outdir:" "$PARAMS_FILE" | cut -d' ' -f2- | tr -d ' ')
    echo "Found existing params file with:"
    echo "  outdir: $EXISTING_OUTDIR"
    echo ""
    read -p "Reuse this S3 bucket? (Y/n): " -n 1 -r
    echo ""
    echo ""

    if [[ $REPLY =~ ^[Nn]$ ]]; then
        # User wants to use new bucket - prompt for it
        echo "Enter S3 bucket path for workflow outputs"
        echo "(e.g., s3://my-bucket/smoke-test-results):"
        read -r S3_BUCKET
    else
        # Reuse existing bucket
        S3_BUCKET="$EXISTING_OUTDIR"
        echo "Reusing: $S3_BUCKET"
        echo ""
    fi
else
    # No existing params file - prompt for S3 bucket
    echo "Enter S3 bucket path for workflow outputs"
    echo "(e.g., s3://my-bucket/smoke-test-results):"
    read -r S3_BUCKET
fi

# Validate S3 bucket format
if [[ ! "$S3_BUCKET" =~ ^s3:// ]]; then
    echo ""
    echo "ERROR: S3 bucket path must start with 's3://'"
    echo "Example: s3://my-bucket/smoke-test-results"
    exit 1
fi

echo ""
echo "Configuration:"
echo "  Pipeline: https://github.com/data-yaml/seqera-smoke-test"
echo "  Profile: smoke"
echo "  Output: $S3_BUCKET"
echo ""

# Confirm before launching
read -p "Launch workflow? (y/N): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 0
fi

echo ""
echo "Launching workflow via Seqera Platform..."
echo ""

# Write params file
cat > "$PARAMS_FILE" <<EOF
outdir: $S3_BUCKET
EOF

echo "Parameters saved to: $PARAMS_FILE"
echo ""

# Launch the workflow
tw launch https://github.com/data-yaml/seqera-smoke-test \
  --workspace="$WORKSPACE" \
  --profile smoke \
  --config seqera.config \
  --params-file "$PARAMS_FILE"

echo ""
echo "========================================"
echo "Workflow Submitted!"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Monitor workflow progress: tw runs list"
echo "2. View workflow details: tw runs view <run-id>"
echo "3. Check logs: tw runs logs <run-id>"
echo "4. Verify S3 output: aws s3 ls $S3_BUCKET/"
echo ""
echo "Note: If you see 'No available compute environment' error,"
echo "you need to configure a compute environment in Seqera Platform."
echo "Use: tw compute-envs list"
echo ""
