#!/bin/bash
set -e

# Parse command line arguments
YES_FLAG=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --yes|-y)
            YES_FLAG=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--yes|-y]"
            exit 1
            ;;
    esac
done

echo "========================================"
echo "Seqera Platform Smoke Test - tw CLI"
echo "========================================"
echo ""

# Load environment variables from .env if it exists
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
    echo "Loading environment variables from $ENV_FILE"
    set -a
    source "$ENV_FILE"
    set +a
    echo ""
fi

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v tw &> /dev/null; then
    echo "ERROR: tw CLI not found. Please install Seqera Platform CLI first."
    echo ""
    echo "Installation:"
    echo "  Homebrew:  brew install seqeralabs/tap/tw"
    echo "  Direct:    https://github.com/seqeralabs/tower-cli/releases/latest"
    echo ""
    echo "See: https://github.com/seqeralabs/tower-cli"
    echo ""
    exit 1
fi

echo "✓ Seqera Platform CLI found"

# Check tw login status
if ! tw info &> /dev/null; then
    echo "ERROR: Not logged in to Seqera Platform."
    echo "Please run: tw login"
    echo ""
    exit 1
fi

echo "✓ Logged in to Seqera Platform"
echo ""

# Check and prompt for TOWER_ACCESS_TOKEN
if [ -z "$TOWER_ACCESS_TOKEN" ]; then
    echo "TOWER_ACCESS_TOKEN not found in environment."
    echo "Enter your Seqera Platform access token:"
    read -r TOWER_ACCESS_TOKEN

    if [ -z "$TOWER_ACCESS_TOKEN" ]; then
        echo "ERROR: TOWER_ACCESS_TOKEN is required."
        exit 1
    fi

    # Save to .env file
    SAVE_TO_ENV=true
fi

echo "✓ TOWER_ACCESS_TOKEN configured"
export TOWER_ACCESS_TOKEN

# Ensure TOWER_ACCESS_TOKEN is written to .env if not already present
if [ ! -f "$ENV_FILE" ] || ! grep -q "^TOWER_ACCESS_TOKEN=" "$ENV_FILE"; then
    SAVE_TO_ENV=true
fi

# Save environment variables to .env if new ones were entered
if [ "$SAVE_TO_ENV" = true ]; then
    echo ""
    echo "Saving credentials to $ENV_FILE for future use..."

    # Create or update .env file
    if [ -f "$ENV_FILE" ] && grep -q "^TOWER_ACCESS_TOKEN=" "$ENV_FILE"; then
        # Update existing token
        grep -v "^TOWER_ACCESS_TOKEN=" "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
        echo "TOWER_ACCESS_TOKEN=$TOWER_ACCESS_TOKEN" >> "${ENV_FILE}.tmp"
        mv "${ENV_FILE}.tmp" "$ENV_FILE"
    else
        # Add token to new or existing file
        if [ -f "$ENV_FILE" ]; then
            # File exists, append token
            echo "TOWER_ACCESS_TOKEN=$TOWER_ACCESS_TOKEN" >> "$ENV_FILE"
        else
            # Create new file with token
            {
                echo "# Seqera Platform credentials"
                echo "# Generated by test-tw.sh on $(date)"
                echo "TOWER_ACCESS_TOKEN=$TOWER_ACCESS_TOKEN"
            } > "$ENV_FILE"
        fi
    fi

    # Ensure .env is in .gitignore
    if [ -f ".gitignore" ]; then
        if ! grep -q "^\.env$" .gitignore; then
            echo ".env" >> .gitignore
            echo "✓ Added .env to .gitignore"
        fi
    else
        echo ".env" > .gitignore
        echo "✓ Created .gitignore with .env"
    fi

    echo "✓ Credentials saved to $ENV_FILE"
fi

echo ""

# Check for workspaces
echo "Checking workspaces..."
tw workspaces list
if [ $? -ne 0 ]; then
    echo "ERROR: Unable to list workspaces."
    exit 1
fi

echo ""

# Check if workspace is already saved
if [ -f "$ENV_FILE" ] && grep -q "^TOWER_WORKSPACE_ID=" "$ENV_FILE"; then
    SAVED_WORKSPACE=$(grep "^TOWER_WORKSPACE_ID=" "$ENV_FILE" | cut -d'=' -f2-)
    echo "Found saved workspace: $SAVED_WORKSPACE"
    echo ""

    if [ "$YES_FLAG" = true ]; then
        WORKSPACE="$SAVED_WORKSPACE"
        echo "Using workspace: $WORKSPACE (--yes flag)"
    else
        read -p "Use this workspace? (Y/n): " -n 1 -r
        echo ""
        echo ""

        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            WORKSPACE="$SAVED_WORKSPACE"
            echo "Using workspace: $WORKSPACE"
        else
            # Prompt for new workspace
            echo "Enter workspace in Organization/Workspace format"
            echo "(e.g., Quilt_Data/hackathon_2023):"
            read -r WORKSPACE

            if [ -z "$WORKSPACE" ]; then
                echo "ERROR: Workspace is required."
                exit 1
            fi

            # Update .env file with new workspace
            grep -v "^TOWER_WORKSPACE_ID=" "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
            echo "TOWER_WORKSPACE_ID=$WORKSPACE" >> "${ENV_FILE}.tmp"
            mv "${ENV_FILE}.tmp" "$ENV_FILE"
            echo "✓ Workspace saved to $ENV_FILE"
        fi
    fi
else
    # No saved workspace - error if --yes flag is used
    if [ "$YES_FLAG" = true ]; then
        echo "ERROR: --yes flag requires TOWER_WORKSPACE_ID in $ENV_FILE"
        echo "Run without --yes first to configure workspace."
        exit 1
    fi

    # Prompt for workspace
    echo "Enter workspace in Organization/Workspace format"
    echo "(e.g., Quilt_Data/hackathon_2023):"
    read -r WORKSPACE

    if [ -z "$WORKSPACE" ]; then
        echo "ERROR: Workspace is required."
        exit 1
    fi

    # Save workspace to .env
    echo ""
    echo "Saving workspace to $ENV_FILE for future use..."
    if [ -f "$ENV_FILE" ]; then
        grep -v "^TOWER_WORKSPACE_ID=" "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
        echo "TOWER_WORKSPACE_ID=$WORKSPACE" >> "${ENV_FILE}.tmp"
        mv "${ENV_FILE}.tmp" "$ENV_FILE"
    else
        echo "TOWER_WORKSPACE_ID=$WORKSPACE" >> "$ENV_FILE"
    fi
    echo "✓ Workspace saved"
fi

echo ""

# Check for compute environments in the workspace
echo "Checking compute environments..."
COMPUTE_ENVS_OUTPUT=$(tw compute-envs list --workspace="$WORKSPACE" 2>&1)

if echo "$COMPUTE_ENVS_OUTPUT" | grep -q "No compute environments found"; then
    echo "⚠ No compute environments found in workspace: $WORKSPACE"
    echo ""
    echo "You need to configure a compute environment before launching workflows."
    echo "Visit Seqera Platform to add a compute environment, or use:"
    echo "  tw compute-envs add --help"
    echo ""
    exit 1
fi

# Display available compute environments
echo "$COMPUTE_ENVS_OUTPUT"
echo ""

# Check if there's a saved compute environment
if [ -f "$ENV_FILE" ] && grep -q "^TOWER_COMPUTE_ENV=" "$ENV_FILE"; then
    SAVED_COMPUTE_ENV=$(grep "^TOWER_COMPUTE_ENV=" "$ENV_FILE" | cut -d'=' -f2-)
    echo "Found saved compute environment: $SAVED_COMPUTE_ENV"
    echo ""

    if [ "$YES_FLAG" = true ]; then
        COMPUTE_ENV="$SAVED_COMPUTE_ENV"
        echo "Using compute environment: $COMPUTE_ENV (--yes flag)"
    else
        read -p "Use this compute environment? (Y/n): " -n 1 -r
        echo ""
        echo ""

        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            COMPUTE_ENV="$SAVED_COMPUTE_ENV"
            echo "Using compute environment: $COMPUTE_ENV"
        else
            # Prompt for new compute environment
            echo "Enter compute environment name from the list above:"
            read -r COMPUTE_ENV

            if [ -z "$COMPUTE_ENV" ]; then
                echo "ERROR: Compute environment is required."
                exit 1
            fi

            # Update .env file with new compute environment
            grep -v "^TOWER_COMPUTE_ENV=" "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
            echo "TOWER_COMPUTE_ENV=$COMPUTE_ENV" >> "${ENV_FILE}.tmp"
            mv "${ENV_FILE}.tmp" "$ENV_FILE"
            echo "✓ Compute environment saved to $ENV_FILE"
        fi
    fi
else
    # No saved compute environment
    if [ "$YES_FLAG" = true ]; then
        # Use default/primary when --yes is set
        COMPUTE_ENV=""
        echo "Using workspace default/primary compute environment (--yes flag)"
    else
        # Prompt for compute environment
        echo "Enter compute environment name from the list above"
        echo "(or press Enter to use primary/default):"
        read -r COMPUTE_ENV

        if [ -n "$COMPUTE_ENV" ]; then
            # Save compute environment to .env
            echo ""
            echo "Saving compute environment to $ENV_FILE for future use..."
            if [ -f "$ENV_FILE" ]; then
                grep -v "^TOWER_COMPUTE_ENV=" "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
                echo "TOWER_COMPUTE_ENV=$COMPUTE_ENV" >> "${ENV_FILE}.tmp"
                mv "${ENV_FILE}.tmp" "$ENV_FILE"
            else
                echo "TOWER_COMPUTE_ENV=$COMPUTE_ENV" >> "$ENV_FILE"
            fi
            echo "✓ Compute environment saved"
        else
            echo "Using workspace default/primary compute environment"
        fi
    fi
fi

echo ""

# Create work directory if it doesn't exist
mkdir -p work
PARAMS_FILE="work/params.yaml"

# Check if params file already exists and offer to reuse
if [ -f "$PARAMS_FILE" ]; then
    EXISTING_OUTDIR=$(grep "^outdir:" "$PARAMS_FILE" | cut -d' ' -f2- | tr -d ' ')
    echo "Found existing params file with:"
    echo "  outdir: $EXISTING_OUTDIR"
    echo ""

    if [ "$YES_FLAG" = true ]; then
        # Reuse existing bucket when --yes is set
        S3_BUCKET="$EXISTING_OUTDIR"
        echo "Reusing: $S3_BUCKET (--yes flag)"
        echo ""
    else
        read -p "Reuse this S3 bucket? (Y/n): " -n 1 -r
        echo ""
        echo ""

        if [[ $REPLY =~ ^[Nn]$ ]]; then
            # User wants to use new bucket - prompt for it
            echo "Enter S3 bucket path for workflow outputs"
            echo "(e.g., s3://my-bucket/smoke-test-results):"
            read -r S3_BUCKET
        else
            # Reuse existing bucket
            S3_BUCKET="$EXISTING_OUTDIR"
            echo "Reusing: $S3_BUCKET"
            echo ""
        fi
    fi
else
    # No existing params file
    if [ "$YES_FLAG" = true ]; then
        echo "ERROR: --yes flag requires existing params file with S3 bucket"
        echo "Run without --yes first to configure S3 bucket."
        exit 1
    fi

    # Prompt for S3 bucket
    echo "Enter S3 bucket path for workflow outputs"
    echo "(e.g., s3://my-bucket/smoke-test-results):"
    read -r S3_BUCKET
fi

# Validate S3 bucket format
if [[ ! "$S3_BUCKET" =~ ^s3:// ]]; then
    echo ""
    echo "ERROR: S3 bucket path must start with 's3://'"
    echo "Example: s3://my-bucket/smoke-test-results"
    exit 1
fi

# Detect current git branch
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null)
if [ -z "$CURRENT_BRANCH" ]; then
    CURRENT_BRANCH="main"
    echo "⚠ Could not detect git branch, defaulting to: $CURRENT_BRANCH"
else
    echo "Detected git branch: $CURRENT_BRANCH"
fi

echo ""

# Get compute environment details if a specific compute env is set
if [ -n "$COMPUTE_ENV" ]; then
    echo "Fetching compute environment details..."
    COMPUTE_ENV_DETAILS=$(tw compute-envs view --name="$COMPUTE_ENV" --workspace="$WORKSPACE" 2>/dev/null)

    # Extract region and workDir from the JSON configuration
    CE_REGION=$(echo "$COMPUTE_ENV_DETAILS" | grep -o '"region" : "[^"]*"' | cut -d'"' -f4)
    CE_WORKDIR=$(echo "$COMPUTE_ENV_DETAILS" | grep -o '"workDir" : "[^"]*"' | cut -d'"' -f4)

    echo ""
fi

echo "Configuration:"
echo "  Pipeline: https://github.com/data-yaml/seqera-smoke-test"
echo "  Branch: $CURRENT_BRANCH"
echo "  Profile: awsbatch"
echo "  Compute Environment: ${COMPUTE_ENV:-default}"
if [ -n "$CE_REGION" ]; then
    echo "  Region: $CE_REGION"
fi
if [ -n "$CE_WORKDIR" ]; then
    echo "  Work Directory: $CE_WORKDIR"
fi
echo "  Output: $S3_BUCKET"
echo ""

# Confirm before launching
if [ "$YES_FLAG" = true ]; then
    echo "Launching workflow (--yes flag)..."
else
    read -p "Launch workflow? (y/N): " -n 1 -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi
fi

echo ""
echo "Launching workflow via Seqera Platform..."
echo ""

# Write params file
cat > "$PARAMS_FILE" <<EOF
outdir: $S3_BUCKET
EOF

echo "Parameters saved to: $PARAMS_FILE"
echo ""

# Launch the workflow with the detected branch and capture output
if [ -n "$COMPUTE_ENV" ]; then
    LAUNCH_OUTPUT=$(tw launch https://github.com/data-yaml/seqera-smoke-test \
      --workspace="$WORKSPACE" \
      --revision="$CURRENT_BRANCH" \
      --compute-env="$COMPUTE_ENV" \
      --profile awsbatch \
      --params-file "$PARAMS_FILE" 2>&1)
    LAUNCH_EXIT_CODE=$?
else
    LAUNCH_OUTPUT=$(tw launch https://github.com/data-yaml/seqera-smoke-test \
      --workspace="$WORKSPACE" \
      --revision="$CURRENT_BRANCH" \
      --profile awsbatch \
      --params-file "$PARAMS_FILE" 2>&1)
    LAUNCH_EXIT_CODE=$?
fi

echo "$LAUNCH_OUTPUT"

# Check if launch failed
if [ $LAUNCH_EXIT_CODE -ne 0 ]; then
    echo ""
    echo "========================================"
    echo "ERROR: Workflow launch failed!"
    echo "========================================"
    echo ""
    exit 1
fi

# Extract run ID from the output (format: "Workflow <RUN_ID> submitted")
RUN_ID=$(echo "$LAUNCH_OUTPUT" | grep -oE '[0-9a-zA-Z]{14}' | head -1)

echo ""
echo "========================================"
echo "Workflow Submitted!"
echo "========================================"
echo ""

if [ -n "$RUN_ID" ]; then
    echo "Run ID: $RUN_ID"
    echo ""
    echo "Next steps:"
    echo "1. View workflow details: tw runs view -i $RUN_ID --workspace='$WORKSPACE'"
    echo "2. View workflow tasks: tw runs view -i $RUN_ID tasks --workspace='$WORKSPACE'"
    echo "3. Verify S3 output: aws s3 ls $S3_BUCKET/"
else
    echo "⚠ Could not extract run ID from output."
    echo ""
    echo "Next steps:"
    echo "1. View workflow details: tw runs view -i <run-id> --workspace='$WORKSPACE'"
    echo "2. View workflow tasks: tw runs view -i <run-id> tasks --workspace='$WORKSPACE'"
    echo "3. Verify S3 output: aws s3 ls $S3_BUCKET/"
fi

echo ""
echo "Note: Workspace saved to $ENV_FILE for next run."
echo "      Remember to use --workspace='$WORKSPACE' with tw commands."
echo ""
echo "If you see 'No available compute environment' error,"
echo "you need to configure a compute environment in Seqera Platform."
echo "Use: tw compute-envs list --workspace='$WORKSPACE'"
echo ""
